#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

wm97xx-ts-y := wm97xx-core.o


#obj-m    += inet_ctp.o

#obj-$(CONFIG_INPUT_TOUCHSCREEN)   += gt9xx/
#obj-$(CONFIG_INPUT_TOUCHSCREEN)   += gt9xxf/
#obj-$(CONFIG_INPUT_TOUCHSCREEN)    += ft5x/

obj-m    += gslx680new/
obj-m     += gslx680/

#obj-m    += ft5x02/
#obj-m    += ft5402/
